# Generated by Django 2.1.15 on 2020-07-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
                ('group_img', models.CharField(max_length=500)),
                ('group_likenum', models.IntegerField()),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_group', to='maps.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=500)),
                ('singer_img', models.CharField(max_length=500)),
                ('singer_likenum', models.IntegerField()),
                ('group_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='singers.Group')),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_singer', to='maps.Spot')),
            ],
        ),
    ]
