# Generated by Django 2.1.15 on 2020-07-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='showman_cnt',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='drama_cnt',
        ),
    ]
