# Generated by Django 2.1.15 on 2020-08-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_sort', models.IntegerField()),
                ('star_groupname', models.CharField(max_length=500)),
                ('star_name', models.CharField(max_length=500)),
                ('star_img', models.CharField(max_length=500)),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_actor', to='maps.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_theme', models.IntegerField()),
                ('visit_spot', models.IntegerField()),
                ('visit_groupname', models.CharField(max_length=500)),
                ('visit_name', models.CharField(max_length=500)),
                ('visit_user', models.IntegerField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_star_king', models.CharField(max_length=500)),
            ],
        ),
    ]
