# Generated by Django 2.1.15 on 2020-07-23 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=500)),
                ('group_img', models.CharField(max_length=500)),
                ('group_cnt', models.ManyToManyField(null=True, related_name='user_show', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Showman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showman_name', models.CharField(max_length=500)),
                ('showman_img', models.CharField(max_length=500)),
                ('show_cd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enters.Show')),
                ('showman_cnt', models.ManyToManyField(null=True, related_name='user_showman', to=settings.AUTH_USER_MODEL)),
                ('spot_cd', models.ManyToManyField(null=True, related_name='spot_show', to='maps.Spot')),
            ],
        ),
    ]
