# Generated by Django 2.1.15 on 2020-07-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='group_cnt',
        ),
        migrations.RemoveField(
            model_name='showman',
            name='showman_cnt',
        ),
    ]
